### ISSUE TITLE
FileNotFoundError: .env not found，could you upload the .env file, thank you.

### ISSUE THREAD

**Issue by csrwang** [Natlem/M-HTCN#2]
Traceback (most recent call last):
  File "exp_traineval_htcn.py", line 7, in <module>
    from experiments.exp_utils import get_config_var, LoggerForSacred, Args
  File "../experiments/exp_utils.py", line 57, in <module>
    all_envs =  get_config_var()
  File "../experiments/exp_utils.py", line 37, in get_config_var
    raise FileNotFoundError('.env not found')
FileNotFoundError: .env not found

Look forward to your reply, thank you

**Comment by csrwang** [comment]
Could you upload the demo of the .env file?

Thank you very much
